language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
script: bundle exec rspec
env:
  global:
  - secure: ZWEQHxs8Pc1PBRqE4oy52IoLOj15TzFra8mh61LpCyluDU228Ovz2bPVxTp/RTzIZRWSug7HjcrYdChCM3NU5XdQqIWMsO+Isrhlp+1qfZZtRl1jDJhGrFI/iHe4+xrvoLuszoBG7ltzHn7vZaP0Jv8T87OYdT64EvKW1SCFmDEmB6VvllwHwOi8YGLv9XSjvb7InI810MCcOeCf223gu+j8eIgdsqJk7l5FCySAdmqSPdyqyW12CAV2W2AQwSwMMlRLohnx5iJRr8sqNpd+G1yi8Zww+d1906oGVoXOUEALxF1RhC0i8hR6RSYFLiyJnbfORqy4bVqcWYgvD9rFxg1O1oa9XEqmKc6BEI2GEe4Ok4RX037xjPpm/jpHib8FETHB772CksBt5nQq5205yKEAtprprmilteXFC/mi5r7vpNpCKMgo+snL4R5/yYOk+pKOUtMn9Vg5X7LhAXcnSyw/ycyBzsVs/mYlqExrGaSvrVaiXvdyHUE8ru1Ldbv8N8o/s9VoZkoWHpkejKufNw0abZKhgCUZyOBLe3y4fWqDS3jOnrJ3TwhuD37tFdLiXe6oO2y2/smsckZz6Be4kJZCiyJR0EHIUFJMppp3i1C8/BJKPzKhdxjJEWFDFuyK62dodrSZhaZM9Zzc7oImZUdPGZBMtSC5wr5kZjX1YV0=
