language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2.0
script: bundle exec rspec
env:
  global:
    secure: m+pw0zMAm1MapoFaiOB1yaWAHofuic+kFR7o8lFZmuiTGXv8ChX9l/CQoHwtmtmXJtrl9KN5UUbyHL5DmEQrMG+YBE1hBKoiJ0cAJNEwiaNDkXGf6ENCKDq5XV0a31fCiXuPw4Ii4ok0i+Pbi7uqX3LjE3r4B6klSJ76GgRjr617xt2mVjhFzcpWdUHt8xpqRsljWAuL7TvJK5ynOGB31ps9Gb1ECsKikbjefxhmJHRo6db2cN0FPjKXa6nfWZjs3XmLdnb1BFrlniCuz6RG3BefCtYiVraLeT/kG3+PVb9V2C5rV0hZ3pI+HjLjj6VUQN5V2XVc6yS8hox+ewjI+TrifyzEmy46FVXU63GWzH2qbbAQvzR6tImT4LhOpJBN8ndCvxTEl38tUFmtRQL3Rj7nNTScjEzz+GjavgDGVcqhTdAEiWNn3WOBD/t0Wo85CjUABLPowyjBuj1OsiETLmGf8GFRmfgSHjj47aKgufu25fwt6Be+XbnIocqsQGNX8NwI3iIPADi4PO1wDBfQMkHQfadHLpOZEoU5zbDl6IbVID9bCPdYKiD5CPoE83Uqcq22lGyLicDQWnu1MsXltUI83Ik6yWPqmCVHSqKX8lpUuu/6kAfhOrcy34Jn1WdaRNKaEP6Vmjp+k2CpD9kJtsq8MGxeHN05oW62kcvqi78=
